### PR TITLE
Initialize kubeshark pinned eBPF resources inside init container

### PR DESCRIPTION
**Pull request by iluxa**

### CODE REVIEW

**Comment by alongir** [comment]
@iluxa should I merge this one?

**Comment by alongir** [comment]
@iluxa is this ready to merge?

**Comment by iluxa** [comment]
> @iluxa is this ready to merge?

Not yet, I need consider to include bpf filesystem mount in the PR

**Comment by iluxa** [comment]
@alongir it's ready for merge

**Review by alongir — APPROVED** [review]

**Pull request merged**
