### PR TITLE
Kubeshark Operator for Openshift

### PR DESCRIPTION
**Pull request by kcns008**
TESTED LOCALLY

### Prerequisites

- Access to Openshift Cluster.
- Login as `cluster-admin`

Go to `KS-Operator` :

Apply Kubeshark CRD

```
oc apply -f config/crd/bases/apps.kubeshark.co_kubesharks.yaml
```

then

```
make run
```

### CODE REVIEW

**Comment by alongir** [comment]
@kcns008 quick question. Does this need to be part of the kubeshark repo or does it make sense to make this its own repo?

**Comment by kcns008** [comment]
@alongir Own repo for kubeshar-operator would be better option.

**Comment by alongir** [comment]
> @alongir Own repo for kubeshar-operator would be better option.

So, let's do that.

**Comment by alongir** [comment]
https://github.com/kubeshark/openshift-operator

**Pull request closed without merging**
